### ISSUE TITLE
Virtual memory exhausted- if we use on Large C file

### ISSUE THREAD

**Issue by alokprasad** [thentenaar/indent#3]
Check if this fix is present in ur src tree 
https://savannah.gnu.org/bugs/?56644

**Comment by thentenaar** [comment]
This is an old tree, and isn't actively maintained. Thanks for the heads-up on the bug report though. Looks like it could possibly be something I overlooked when I made those changes way back when. Not sure if the maintainers are monitoring the savannah bugtracker, so if you were looking to have that patch included upstream, it's probably a better idea to send it to the mailing list.
